spring: 
  devtools:
    restart:
      enabled: true
    remote:
      debug:
        enabled: true 
  application:
    name: demo
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
server:
  port: 8088
